// IWritableAdapter — `omem migrate` writer surface.
//
// Composed onto adapters that support migration; read-only adapters simply
// don't implement it. See `specs/iwritable-adapter-mini-spec.md` for the
// full design rationale.

import type { MemoryRecord } from './index';

/** Declares which on-disk/host format build the writer targets. */
export interface AdapterFormatCapability {
  /** Same string family as scan / doctor (`claude-code/2026-05`, …). */
  readonly writeSchemaId: string;
  /**
   * Monotonic semver for *our* emitter. Bump when emitted JSON shape changes.
   * Distinct from host tool versioning — host may change silently; we only
   * control our emitter.
   */
  readonly emitterVersion: `${number}.${number}.${number}`;
  /**
   * Conflict policies the writer supports for `--apply`. The orchestrator
   * refuses unsupported policies up front (saves a probe round-trip).
   * `skip-on-conflict` is required for every writer; `overwrite` is opt-in.
   */
  readonly supportedPolicies: readonly ConflictPolicy[];
}

export type MigrateStrategy = 'copy' | 'move' | 'link';

/** CLI `--on-conflict` → orchestrator-owned policy. */
export type ConflictPolicy = 'skip-on-conflict' | 'overwrite' | 'newest-wins';

export interface MigrateFilters {
  readonly since?: Date;
  /** Resolved absolute path hint (tool-specific semantics in adapter notes). */
  readonly projectPath?: string;
  readonly sessionId?: string;
}

/**
 * Exactly one of dryRun modes. Default migration command emits `dry-run`.
 * exactOptionalPropertyTypes-friendly: callers MUST omit `mode` rather than
 * passing undefined when defaulting.
 */
export type MigrateMode =
  | { readonly kind: 'dry-run' }
  | {
      readonly kind: 'apply';
      /**
       * When stdout is non-TTY OR `OMEM_NON_INTERACTIVE=1`, must be true so
       * scripts cannot accidentally `--apply` without explicit consent.
       */
      readonly approvedDestWrite: boolean;
    };

export interface MigrateContext {
  readonly signal?: AbortSignal;
  readonly filters: MigrateFilters;
  readonly strategy: MigrateStrategy;
  readonly conflictPolicy: ConflictPolicy;
  readonly mode: MigrateMode;
}

/** One logical append to a destination transcript file (or SaaS batch later). */
export interface WriteInstruction {
  /** Stable trace id for manifest (UUID v4 generated by orchestrator). */
  readonly operationId: string;
  readonly record: MemoryRecord;
  readonly sourceAdapterId: string;
  readonly sourceFingerprint: string;
}

export interface WriteBatch {
  readonly instructions: readonly WriteInstruction[];
}

export interface WriteProbeResult {
  /** If false — migrate refuses `--apply`; dry-run still allowed. */
  readonly canWrite: boolean;
  readonly reason?: string;
  /** Host dir exists, quotas, writable test file succeeded, denylist clearance, etc. */
  readonly diagnostics?: Readonly<Record<string, unknown>>;
}

export interface PreparedWritePlan {
  /** Files the adapter intends to create or append-with-lock. */
  readonly targetPaths: readonly string[];
  /** Byte-size estimate per path (best-effort, for UX only). */
  readonly estimatedBytesByPath?: Readonly<Record<string, number>>;
}

export type WriteFailureReason =
  | 'conflict-id'
  | 'conflict-fingerprint'
  | 'format-unsupported'
  | 'probe-failed'
  | 'filtered'
  | 'denylisted'
  | 'io-error'
  | 'policy-unsupported'
  | 'dry-run';

export interface WriteBatchResultItem {
  readonly operationId: string;
  readonly status: 'written' | 'skipped' | 'failed';
  readonly reason?: WriteFailureReason;
  readonly destPath?: string;
}

export interface WriteBatchReceipt {
  readonly items: readonly WriteBatchResultItem[];
}

export interface IWritableAdapter {
  readonly writeCapability: AdapterFormatCapability;

  /**
   * Cheap pre-flight before any record work. MUST NOT mutate host data.
   * Called once per migrate invocation.
   */
  probeWrite(ctx: MigrateContext): Promise<WriteProbeResult>;

  /**
   * Confirm our emitter matches expectations for the *current* probe of on-disk
   * samples. Implementation may read ≤ N lines from existing transcripts
   * (streaming), never the full tree.
   */
  validateWritableFormat?(ctx: MigrateContext): Promise<{
    readonly ok: boolean;
    readonly reason?: string;
  }>;

  /** Plan FS paths touched if apply proceeds — for manifest + rollback + preview. */
  planWrites(batch: WriteBatch, ctx: MigrateContext): Promise<PreparedWritePlan>;

  /** Execute one batch. Idempotent on operationIds where the adapter can manage it. */
  writeBatch(batch: WriteBatch, ctx: MigrateContext): Promise<WriteBatchReceipt>;
}

export function isWritableAdapter(v: unknown): v is IWritableAdapter {
  if (v === null || typeof v !== 'object') return false;
  const o = v as Record<string, unknown>;
  const cap = o.writeCapability as AdapterFormatCapability | undefined;
  return (
    cap !== undefined &&
    typeof cap === 'object' &&
    cap !== null &&
    typeof cap.writeSchemaId === 'string' &&
    typeof cap.emitterVersion === 'string' &&
    Array.isArray(cap.supportedPolicies) &&
    typeof o.probeWrite === 'function' &&
    typeof o.planWrites === 'function' &&
    typeof o.writeBatch === 'function'
  );
}

/**
 * Reserved metadata keys that the migration orchestrator and writers may set
 * on `MemoryRecord.metadata`. Adapters that round-trip foreign metadata
 * verbatim should preserve these; strict-schema hosts (Claude Code) may need
 * to strip them before writing JSON to disk — in that case keep the keys
 * only in the manifest.
 */
export const MIGRATION_METADATA_KEYS = {
  ORIGINAL_SOURCE: 'omem.migration.originalSource',
  ORIGINAL_STABLE_KEY: 'omem.migration.originalStableKey',
  IMPORTED_AT: 'omem.migration.importedAt',
  EMITTER_VERSION: 'omem.migration.emitterVersion',
} as const;
